//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_Transporte
    {
        public int id { get; set; }
        public int usuarioId { get; set; }
        public int transporteId { get; set; }
    
        public virtual Transporte Transporte { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
